global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "communication-scheduling-api"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["app:8080"]
        labels:
          application: "communication-scheduling-api"